version: "1.0"

jobs:
  main:
    executor: local
    commands:
      - crystal --version
    needs:
      - crystal

  crystal:
    description: "Install Crystal"
    executor: local
    variables:
      VERSION: "0.36.1"
    commands:
      - apk add --no-cache curl
      - |
        curl -L "https://github.com/crystal-lang/crystal/releases/download/${VERSION}/crystal-${VERSION}-1-linux-x86_64.tar.gz" | 
        tar -zx -C /usr --strip-component=1 \
        --exclude */lib/crystal/lib \
        --exclude */share/crystal/src/llvm/ext/llvm_ext.o \
        --exclude */share/crystal/src/ext/libcrystal.a
      - cd /usr/share/crystal && cc -fPIC -c -o src/ext/sigfault.o src/ext/sigfault.c && ar -rcs src/ext/libcrystal.a src/ext/sigfault.o
    needs:
      - system

  system:
    description: "Install system dependencies"
    executor: local
    commands:
      - |
        apk add --update --no-cache --force-overwrite gc-dev gcc gmp-dev libatomic_ops libevent-static musl-dev pcre-dev \
        libxml2-dev openssl-dev openssl-libs-static tzdata yaml-static zlib-static make git