version: "1.0"

jobs:
  main:
    needs:
      - git
      - extensions
  
  git:
    commands:
      - git config --global user.name "Tudor Marghidanu"
      - git config --global user.email tudor@marghidanu.com

  prerequisites:
    commands:
      - >
        sudo apk add --no-cache 
        openssl-dev yaml-dev
        yq@community
  
  extensions:
    commands:
      - code-server --install-extension faustinoaq.crystal-lang
    needs:
      - prerequisites
